version: '3.8'
services:
  api:
    build: .
    container_name: HrSystemApi
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HrSystemDb;User Id=sa;Password=NewStrongP@ssw0rd;TrustServerCertificate=True

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: SQL
    hostname: sqlserver
    ports :
      - "1433:1433"
    environment:
      SA_PASSWORD: "NewStrongP@ssw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

  migrations:
    build: .
    container_name: MigrationService
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HrSystemDb;User Id=sa;Password=NewStrongP@ssw0rd;TrustServerCertificate=True
    command: >
      bash -c "
      dotnet restore &&
      dotnet ef migrations add InitialCreate &&
      dotnet ef database update"
    volumes:
      - .:/app

volumes:
  sql_data:



# version: '3.8'

# services:
#   api:
#     build: .
#     environment:
#       - ConnectionStrings__DefaultConnection=Server=db;Database=VSDB;User Id=sa;Password=NewStrongP@ssw0rd;TrustServerCertificate=True;
#     ports:
#       - "8081:8080"
#     depends_on:
#       - db

#   db:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     environment:
#       SA_PASSWORD: "NewStrongP@ssw0rd"
#       ACCEPT_EULA: "Y"
#     ports:
#       - "8082:1433"
#     volumes:
#       - sqlvolume:/var/opt/mssql

# volumes:
#   sqlvolume:
